<style>
    #nette-debug .nette-githubApiPanel,
    #tracy-debug .nette-githubApiPanel { min-width: 700px; }
    #nette-debug .nette-githubApiPanel h2,
    #tracy-debug .nette-githubApiPanel h2 { font-size: 22px; font-weight: bold; }
    #nette-debug .nette-githubApiPanel table,
    #tracy-debug .nette-githubApiPanel table { width: 100%; }
    #nette-debug .nette-githubApiPanel table th,
    #tracy-debug .nette-githubApiPanel table th { width: 80px; }
</style>

<h1>Queries: <?php echo $esc(count($this->calls)); ?>, time: <?php echo $esc($totalTime); ?> </h1>
<div class="nette-inner tracy-inner nette-githubApiPanel">
	<?php foreach($this->calls as $call): ?>
		<h2><?php echo $esc(strtoupper((string) $call->info['method'])); ?> <?php echo $esc((string) $call->url); ?></h2>
		<table>
			<tr><th>Time</th><td><?php echo $esc(number_format($call->time * 1000, 2, '.', ' ')) ?>&nbsp;ms</td></tr>
			<tr><th>Response</th><td><?php echo $click($call->result ?: $call->exception, TRUE); ?></td></tr>
			<tr><th>Params</th><td><?php echo $click($call->params, TRUE); ?></td></tr>
			<tr><th>Info</th><td><?php echo $click($call->info, TRUE); ?></td></tr>
		</table>
	<?php endforeach; ?>
</div>
